//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "nodes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub country_code: String,
    pub city: String,
    pub title: String,
    pub description: Option<String>,
    pub latitude: Decimal,
    pub longitude: Decimal,
    pub trip: i32,
    pub created_by: i32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::trips::Entity",
        from = "Column::Trip",
        to = "super::trips::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Trips,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::trips::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trips.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
