//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::nodes::Entity as Nodes;
pub use super::trips::Entity as Trips;
pub use super::user_trips::Entity as UserTrips;
pub use super::users::Entity as Users;
